### ISSUE TITLE
RimWorld (Linux)

### ISSUE THREAD

**Issue by ptitSeb** [ptitSeb/box86-compatibility-list#115]
### Description
Runs fine

### Tested on
Pythium+RX550 running Debian 11
ODroid N2 running Armbian/TwisterOS

### Status
**Previous behavior:** 
None

**Current behavior:**
Runs fine

### Screenshots
![image](https://user-images.githubusercontent.com/3250792/142694925-56423f84-e7b0-45b2-8e05-e1ee7bb84da5.png)

### OpenGL
OpenGL 3.2+

### Additional Information
Need Box64 v0.1.6+

**Comment by 220242** [comment]
With (Mod)framework [harmony ](https://github.com/pardeike/HarmonyRimWorld) i have a black screen. 
This framework needed for [RimThreaded ](https://github.com/cseelhoff/RimThreaded). RimThreaded enables RimWorld to utilize multiple threads.
On pinebook pro.
Can you check, have you a same problem?

**Comment by ptitSeb** [comment]
I reproduce, but this is not the place to open box64 issue.

**Comment by 220242** [comment]
I tried it on clear armbian and latest box64. The game started with modifications. RimThreaded does not control multiple threads on rk3399 or on a linux. =(

**Comment by ptitSeb** [comment]
> I tried it on clear armbian and latest box64. The game started with modifications. RimThreaded does not control multiple threads on rk3399 or on a linux. =(

How do you know?

**Comment by ptitSeb** [comment]
Closing in favor of https://github.com/ptitSeb/box86-compatibility-list/issues/213
