### ISSUE TITLE
Half-life 2 (Linux)

### ISSUE THREAD

**Issue by Moldytzu** [ptitSeb/box86-compatibility-list#119]
### Description
Game runs fine.

### Tested on
ASUS Tinker Board 1
RPi 4

### Status
**Previous behavior:** 
The game tries to start, creates a window and then crashes. And the terminal is spammed with stdshader_dx0 thru stdshader_dx8.so dlopen errors. (ASUS Tinker Board 1)

**Current behavior:**
Game runs fine. Installed thru Steam. (RPi 4)

### OpenGL
3.0

**Comment by Hacker1245** [comment]
Do you have Steam running on the SBC?

**Comment by Moldytzu** [comment]
I can't get it to run as the kernel that ships with the operating system doesn't support binfmt :/ I will try today to recompile the kernel and enable that feature

**Comment by Heasterian** [comment]
Game is fully playable on Poco F1 with Mobian, installed using Steam. I'll post screens other day.

**Comment by Moldytzu** [comment]
The game is fully playable on the RPi 4, installed using Steam

**Comment by ptitSeb** [comment]
Lacking screenshots, so closing in favor of https://github.com/ptitSeb/box86-compatibility-list/issues/348
