### ISSUE TITLE
Update box86-compatibility-list to represent both box86 and box64.

### ISSUE THREAD

**Issue by Raezroth** [ptitSeb/box86-compatibility-list#136]
Box64 tag has been in use for a while now, quite a few programs and games work in box64. It maybe time to consider updating the compatibility list to represent both. I've thought of a few possibilities:

box86/64-compatibility-list
box86/box64-compatibility-list
b86/b64-compatibility-list

Please Close When Done

**Comment by ptitSeb** [comment]
Despite the "box86" name, the compatibility list is for both box86 and box64.
You can see there also: https://box86.org/app/ that the compatibility list tickets are also used as a database.
I'm unsure of what is you request? box86 and box64 tags alreadt exist to differentiate wich engine is used
