### ISSUE TITLE
Half-Life 2

### ISSUE THREAD

**Issue by talraash** [ptitSeb/box86-compatibility-list#21]
### Description

```
Not working
```

### Tested on

RPi4+gl4es
### Status
**Previous behavior:** 

**Current behavior:**

Not start

### OpenGL

OpenGL 2.x, S3TC
### Additional Information

Require libtcmalloc_minimal.so.4:i386

Could not find required OpenGL entry point 'glBindProgramARB'! Either your video card is unsupported, or your OpenGL driver needs to be updated.

**Comment by parkerlreed** [comment]
What happens if you try without gl4es? The RPi4 with FKMS does kinda support OpenGL 2.

**Comment by talraash** [comment]
Could not find required OpenGL entry point 'glBindProgramARB'! Either your video card is unsupported, or your OpenGL driver needs to be updated. Without gl4es it need s3tc

**Comment by parkerlreed** [comment]
Ahh sorry. Good to know.

**Comment by pinilpypinilpy** [comment]
have to tried setting mat_compressedtextures ?
(in the autoexec.cfg)
It should force hl2 to not use compressed textures
Alernatively, you could try decompressing the testtures yourself
Worth a shot I guess

**Comment by Askmewho** [comment]
Use the latest driver to get s3tc support on mesa. It's on nighthawk/iraspbian for preload on /home/pi or just compile master mesa

**Comment by talraash** [comment]
> Use the latest driver to get s3tc support on mesa. It's on nighthawk/iraspbian for preload on /home/pi/mesa or just compile master mesa

And it's seq fault(steam failure?).

**Comment by Askmewho** [comment]
Yes, there is something else

**Comment by artdeell** [comment]
Should definitely try Regal with HL2.

**Comment by ptitSeb** [comment]
> Should definitely try Regal with HL2.

Is that a joke?

**Comment by artdeell** [comment]
> > Should definitely try Regal with HL2.
> 
> Is that a joke?

No, since it runs with Regal. In official Valve port for Android.

**Comment by artdeell** [comment]
With huge graphical artifacts on non-Tegras but still.

**Comment by ptitSeb** [comment]
But Regal needs the recompiling the source with Regal, it's not a binary repalcement for libGL.so like gl4es. You have the sources to rebuild them?

**Comment by TuxThePenguin0** [comment]
I tested HL2 on my Pinebook Pro, it mostly seems to work fine although in the opening cutscene the graphics get pretty messed up, after that it looks normal though.

**Comment by clort81** [comment]
Mali g52 mp4 is too weak.  Need a good bit more oomph.  7 fps in City 17 in front of train station.

**Comment by ptitSeb** [comment]
Closing in favor of https://github.com/ptitSeb/box86-compatibility-list/issues/348
