### ISSUE TITLE
Death Trash (Native)

### ISSUE THREAD

**Issue by ricoazzurro** [ptitSeb/box86-compatibility-list#261]
### Description
Death Trash, v0.8.7.8 (62607), Linux x64, GOG, Engine: FMOD, Unity

Box64 with Dynarec v0.2.3 b6be4f8

Rock 5B, LFS, BSP kernel 5.10.110+ rkr3.4, Gnome 44.0
PAN_MESA_DEBUG=gofaster,gl3
1080p, default game setting

**NOT working.**

I can not load game assets, eg. the charactor is shown as big white square

Seems I cannot play all **fmod** games.

![death_trash-1](https://user-images.githubusercontent.com/108268247/234712392-fa9481ae-49fe-4fd2-a535-070bef1cb01a.png)

```bash

```

### Tested on

Rock 5B, LFS, BSP kernel 5.10.110+ rkr3.4, Gnome 44.0
PAN_MESA_DEBUG=gofaster,gl3
1080p, default game setting

### Status
**Previous behavior:** 

**Current behavior:**

NOT working. 

### Screenshots

![death_trash-2](https://user-images.githubusercontent.com/108268247/234712607-beb92742-2523-44fc-abbd-47b5c2d30375.png)

### OpenGL

Unity engine build: 2020.3.32f1

### Additional Information

https://www.pcgamingwiki.com/wiki/Death_Trash

**Comment by ptitSeb** [comment]
FMod is a sound engine. I think the issues are Pnafrost related and not box64 related.

**Comment by TheChriggu** [comment]
Hi,
dev working on Death Trash here.
Don't know how much my info is useful here, but from the screenshots I'm pretty sure it has to do with how we render the characters multiple times, to combine rotated weapon sprites, character sprites and do the proper pixel alignment. 
Could be either a shader issue, or something with how Unity renders to textures, or something about the buffer size on the GPU. Pretty sure it's not fmod though.
I'm not really into emulation, and - again - don't know if this is the right place for this. But if there's anything I can do to help, hit me up.

**Comment by ptitSeb** [comment]
@TheChriggu oh, welcome here! Thank you for your input :)

My guess it's indeed a GPU issue. On the RK3588 board used here, the GPU driver is very experimental, so that would make sense yes. I have to try the game demo on my reference machine (still arm, but with a radeon graphic card) to validate if it's a panfrost issue.

**Comment by ricoazzurro** [comment]
Working now by upgrading the board's kernel gpu to `panthor` and userland mesa to mainline `24.1.0`.
I'll close this one by posting the below new one.
https://github.com/ptitSeb/box86-compatibility-list/issues/449
