### ISSUE TITLE
Add search menu in list

### ISSUE THREAD

**Issue by Ilya114** [ptitSeb/box86-compatibility-list#272]
This does not apply to adding a game to the list, but I want to suggest adding a search menu for a specific game, since there are a lot of them and it is inconvenient to search for each one on each page (oh, it`s on site...)

**Comment by ptitSeb** [comment]
@rajdakin any idea if it can be done?

**Comment by rajdakin** [comment]
It's done! The search bar is pretty rudimentary (set everything to upper case, remove spaces, search for the query in the title name), but it works on my side.

**Comment by Ilya114** [comment]
Thanks, it working
