### ISSUE TITLE
They Bleed Pixels.

### ISSUE THREAD

**Issue by MrRKernelPanic** [ptitSeb/box86-compatibility-list#30]
Compatability List says works fine.  Downloaded from Itch.io

sudo box86 ./TheyBleedPixels
Dynarec for ARM, with extension: HALF FAST_MULT EDSP NEON VFPv4 IDIVA PageSize:4096
Using default BOX86_LD_LIBRARY_PATH: ./:lib/:lib32/:x86/
Using default BOX86_PATH: ./:bin/
Counted 20 Env var
Looking for ./TheyBleedPixels
Not an 32bits ELF (2)
Error: reading elf header of ./TheyBleedPixels

**Comment by ptitSeb** [comment]
I checked the Itch.io version, and it's a 64bits binary only. So it's no go there. use `file TheyBleedPixels` in the game folder and it will tell you it's an x86_64 ELF binary: `TheyBleedPixels: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked (uses shared libs), for GNU/Linux 2.6.32, not stripped`

(also, you probably don't need `sudo` to launch box86. And if you installed box86 with `sudo make install` you don't even need to use `box86`, it will get used automaticaly on x86 binary)

**Comment by talraash** [comment]
I used steam version for test...

**Comment by MrRKernelPanic** [comment]
They have since added the 32 Bit version however it generates this error...

Dynarec for ARM, with extension: HALF FAST_MULT EDSP NEON VFPv4 IDIVA PageSize:4096
Using default BOX86_LD_LIBRARY_PATH: ./:lib/:lib32/:x86/
Using default BOX86_PATH: ./:bin/
Counted 46 Env var
Looking for theybleedpixels.x86
Using native(wrapped) libSDL2-2.0.so.0
Using native(wrapped) libdl.so.2
Using native(wrapped) libm.so.6
Using native(wrapped) librt.so.1
Using native(wrapped) libpthread.so.0
Using emulated libSDL2_ttf-2.0.so.0
Using native(wrapped) libfreetype.so.6
Using native(wrapped) libc.so.6
Using native(wrapped) ld-linux.so.2
Error: Symbol FT_Glyph_Stroke not found, cannot apply R_386_JMP_SLOT @0xb6f45da4 (0x1486) in libSDL2_ttf-2.0.so.0
Using emulated libfmod.so.5
Using emulated /usr/lib/i386-linux-gnu/libstdc++.so.6
Using emulated /usr/lib/i386-linux-gnu/libgcc_s.so.1
Warning: Weak Symbol _ZGTtnaj not found, cannot apply R_386_JMP_SLOT @0xb5d7819c (0x6b506)
Warning: Weak Symbol _ZGTtdlPv not found, cannot apply R_386_JMP_SLOT @0xb5d78478 (0x6c076)
Using emulated libfmodstudio.so.5
Using native(wrapped) libopenal.so.1
Couldn't find XDG_DATA_HOME.
Fall back to hardcoded ~/.local/share/.
Using native(wrapped) libasound.so.2
FMOD: Number of drivers: 23
	Driver #0: default
ALSA lib pulse.c:243:(pulse_connect) PulseAudio: Unable to connect: Connection refused

	Driver #1: pulse
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
	Driver #2: jack
	Driver #3: output
	Driver #4: input
	Driver #5: sysdefault:CARD=b1
	Driver #6: dmix:CARD=b1,DEV=0
ALSA lib pcm_dsnoop.c:575:(snd_pcm_dsnoop_open) The dsnoop plugin supports only capture stream
	Driver #7: dsnoop:CARD=b1,DEV=0
	Driver #8: hw:CARD=b1,DEV=0
	Driver #9: plughw:CARD=b1,DEV=0
ALSA lib pcm_usb_stream.c:508:(_snd_pcm_usb_stream_open) Unknown field hint
	Driver #10: usbstream:CARD=b1
	Driver #11: sysdefault:CARD=b2
	Driver #12: dmix:CARD=b2,DEV=0
ALSA lib pcm_dsnoop.c:575:(snd_pcm_dsnoop_open) The dsnoop plugin supports only capture stream
	Driver #13: dsnoop:CARD=b2,DEV=0
	Driver #14: hw:CARD=b2,DEV=0
	Driver #15: plughw:CARD=b2,DEV=0
ALSA lib pcm_usb_stream.c:508:(_snd_pcm_usb_stream_open) Unknown field hint
	Driver #16: usbstream:CARD=b2
	Driver #17: sysdefault:CARD=Headphones
	Driver #18: dmix:CARD=Headphones,DEV=0
ALSA lib pcm_dsnoop.c:575:(snd_pcm_dsnoop_open) The dsnoop plugin supports only capture stream
	Driver #19: dsnoop:CARD=Headphones,DEV=0
	Driver #20: hw:CARD=Headphones,DEV=0
	Driver #21: plughw:CARD=Headphones,DEV=0
ALSA lib pcm_usb_stream.c:508:(_snd_pcm_usb_stream_open) Unknown field hint
	Driver #22: usbstream:CARD=Headphones
FMOD: Using Driver 0
Segmentation fault

**Comment by ptitSeb** [comment]
It seems to be working now on my Pandora. Can you check again (I have made some change in elfloader that may have fixed it).

**Comment by MrRKernelPanic** [comment]
Did a git pull, remade and made install.  Still no joy, it seems to get a little further but same error.  I tried with NuclearThrone, similar thing.

Dynarec for ARM, with extension: HALF FAST_MULT EDSP NEON VFPv4 IDIVA PageSize:4096
Using default BOX86_LD_LIBRARY_PATH: ./:lib/:lib32/:x86/
Using default BOX86_PATH: ./:bin/
Counted 20 Env var
Looking for theybleedpixels.x86
Using native(wrapped) libSDL2-2.0.so.0
Using native(wrapped) libdl.so.2
Using native(wrapped) libm.so.6
Using native(wrapped) librt.so.1
Using native(wrapped) libpthread.so.0
Using emulated libSDL2_ttf-2.0.so.0
Using native(wrapped) libfreetype.so.6
Using native(wrapped) libc.so.6
Using native(wrapped) ld-linux.so.2
Using emulated libfmod.so.5
Using emulated /usr/lib/i386-linux-gnu/libstdc++.so.6
Using emulated /usr/lib/i386-linux-gnu/libgcc_s.so.1
Using emulated libfmodstudio.so.5
Using native(wrapped) libopenal.so.1
Couldn't find XDG_DATA_HOME.
Fall back to hardcoded ~/.local/share/.
Couldn't find XDG_CONFIG_HOME.
Fall back to hardcoded ~/.config/.
Using native(wrapped) libasound.so.2
FMOD: Number of drivers: 23
	Driver #0: default:CARD=Headphones
ALSA lib pulse.c:243:(pulse_connect) PulseAudio: Unable to connect: Connection refused

	Driver #1: pulse
	Driver #2: default:CARD=b1
	Driver #3: sysdefault:CARD=b1
	Driver #4: dmix:CARD=b1,DEV=0
ALSA lib pcm_dsnoop.c:575:(snd_pcm_dsnoop_open) The dsnoop plugin supports only capture stream
	Driver #5: dsnoop:CARD=b1,DEV=0
	Driver #6: hw:CARD=b1,DEV=0
	Driver #7: plughw:CARD=b1,DEV=0
ALSA lib pcm_usb_stream.c:508:(_snd_pcm_usb_stream_open) Unknown field hint
	Driver #8: usbstream:CARD=b1
	Driver #9: default:CARD=b2
	Driver #10: sysdefault:CARD=b2
	Driver #11: dmix:CARD=b2,DEV=0
ALSA lib pcm_dsnoop.c:575:(snd_pcm_dsnoop_open) The dsnoop plugin supports only capture stream
	Driver #12: dsnoop:CARD=b2,DEV=0
	Driver #13: hw:CARD=b2,DEV=0
	Driver #14: plughw:CARD=b2,DEV=0
ALSA lib pcm_usb_stream.c:508:(_snd_pcm_usb_stream_open) Unknown field hint
	Driver #15: usbstream:CARD=b2
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
	Driver #16: jack
	Driver #17: sysdefault:CARD=Headphones
	Driver #18: dmix:CARD=Headphones,DEV=0
ALSA lib pcm_dsnoop.c:575:(snd_pcm_dsnoop_open) The dsnoop plugin supports only capture stream
	Driver #19: dsnoop:CARD=Headphones,DEV=0
	Driver #20: hw:CARD=Headphones,DEV=0
	Driver #21: plughw:CARD=Headphones,DEV=0
ALSA lib pcm_usb_stream.c:508:(_snd_pcm_usb_stream_open) Unknown field hint
	Driver #22: usbstream:CARD=Headphones
FMOD: Using Driver 0

Is there any further debug or information I can supply?

**Comment by ptitSeb** [comment]
You are on a pi4?

**Comment by MrRKernelPanic** [comment]
Yup, running on Pi4, Buster.  run using box68 using the .x86 as you mentioned.  Do you need to have pulseaudio running to use Box86.  Ah hold on, I didn't set the root folder.  It worked, right I realised I had to be in the folder, but call it from within that directory I was navigating right down to the x86 file, not the folder above.  Working now, but the sound is VERY loud.  (not game and music) just the titles.  But progress.  Thanks for taking the time.

**Comment by MrRKernelPanic** [comment]
e.g. `cd /usr/local/games/theybleedpixels/x86`
then
`box86 theybleedpixels.x86'
Won't work

but `cd /usr/local/games/theybleedpixels`
then
`box86 x86/theybleedpixels.x86`

does work.
