### ISSUE TITLE
The Universim (Native)

### ISSUE THREAD

**Issue by ricoazzurro** [ptitSeb/box86-compatibility-list#493]
### Description

The Universim, v1.0.00.46368 (71233), Linux x64, GOG, Engine: Unity

Box64 with Dynarec v0.2.7 1c7e620
Rock 5B, LFS, Kernel rk-6.1-rkr1-panthor-v6, Mesa 24.1.0, Gnome 46

- Not working.
- Stuck at the logo/loading page, however can still hear the background music playing.
- Tested `LIBGL_ALWAYS_SOFTWARE=1` and `-force-opengl`, same.
- Maybe it's a vulkan only game or the requirements are just way too higher for this board.
From the game website,
> Graphics: GTX 780/880M/960/1050Ti/1660/2060 or AMD R9 290 / RX 570. Intel Graphics not supported.

Error Log,
```bash
rico [ /opt/games/the_universim ]$ ./box64-start.sh 
Dynarec for ARM64, with extension: ASIMD AES CRC32 PMULL ATOMICS SHA1 SHA2 PageSize:4096 Running on Cortex-A55 Cortex-A76 with 8 Cores
Will use Hardware counter measured at 24.0 MHz emulating 3.0 GHz
Params database has 66 entries
Box64 with Dynarec v0.2.7 1c7e620 built on Apr 27 2024 02:47:36
BOX64: Detected 48bits at least of address space
Counted 63 Env var
BOX64 LIB PATH: ./:lib/:lib64/:x86_64/:bin64/:libs64/:/lib/x86_64-linux-gnu/:/usr/lib/x86_64-linux-gnu/
BOX64 BIN PATH: ./:bin/:/opt/rustc/bin/:/usr/local/bin/:/usr/bin/:/opt/ant/bin/:/opt/jdk/bin/:/opt/bin/
Looking for ./The Universim.x86_64
argv[1]="-force-opengl"
Rename process to "The Universim.x86_64"
Using emulated UnityPlayer.so
Using native(wrapped) libm.so.6
Using emulated /lib/x86_64-linux-gnu/libgcc_s.so.1
Using native(wrapped) libpthread.so.0
Using native(wrapped) libc.so.6
Using native(wrapped) ld-linux-x86-64.so.2
Using native(wrapped) libdl.so.2
Using native(wrapped) libutil.so.1
Using native(wrapped) librt.so.1
Using native(wrapped) libbsd.so.0
Error: Global Symbol _ULx86_64_local_addr_space not found, cannot apply R_X86_64_GLOB_DAT @0x7fff02016638 ((nil)) in UnityPlayer.so
Found path: /opt/games/the_universim/The Universim.x86_64
Loading in SingleInstance mode
Using native(wrapped) libX11.so.6
Using native(wrapped) libxcb.so.1
Using native(wrapped) libXau.so.6
Using native(wrapped) libXdmcp.so.6
Using native(wrapped) libXext.so.6
Using native(wrapped) libXcursor.so.1
Using native(wrapped) libXfixes.so.3
Using native(wrapped) libXrender.so.1
Using native(wrapped) libXinerama.so.1
Using native(wrapped) libXi.so.6
Using native(wrapped) libXrandr.so.2
Using native(wrapped) libXss.so.1
Using native(wrapped) libXxf86vm.so.1
Using native(wrapped) libGL.so.1
Using emulated /lib/x86_64-linux-gnu/libstdc++.so.6
Using native(wrapped) libudev.so.1
./box64-start.sh: line 24:  6428 Killed                  LIBGL_ALWAYS_SOFTWARE=1 box64 ./"The Universim.x86_64" -force-opengl
```

### Tested on

- Box64 with Dynarec v0.2.7 1c7e620
- Radxa Rock 5B, (RK3588, Cortex-A76+Cortex-A55, Mali-G610)
- LFS r12.1-30
BSP Kernel 6.1.43+ (rk-6.1-rkr1-panthor-v6 6bd0bc6)
Mesa 24.1.0-devel (git-e5f133ccc4)
Gnome 46, Mutter-46.1
- 1080p, Default game settings

### Status
**Previous behavior:** 

None reported.

**Current behavior:**

Not working.

### OpenGL

Unity3D: v2019.4.31f1

### Additional Information

https://crytivo.com/en/the-universim
https://www.gog.com/game/the_universim
https://store.steampowered.com/app/352720/The_Universim/
https://www.pcgamingwiki.com/wiki/The_Universim

**Comment by ksco** [comment]
So I have this game working on my LoongArch machine (using the experimental LA64 DynaRec of course).

<img width="960" alt="screenshot" src="https://github.com/user-attachments/assets/1acee964-cc1c-48af-9939-5a961cc9de9a">

So I think this is less likely a box64 issue, maybe someone can try this game on some AArch64 machine with a decent GPU.

**Comment by ksco** [comment]
Gameplay:
<img width="960" alt="Screenshot_20240716_024721" src="https://github.com/user-attachments/assets/69acfb13-515f-43cf-9edf-a025601c7896">

**Comment by ricoazzurro** [comment]
No luck for me.
I'll test it again when vulkan is ready for my gpu of the board.

Enjoy coding. muahahahahahaha.

**Comment by ricoazzurro** [comment]
> So I have this game working on my LoongArch machine (using the experimental LA64 DynaRec of course).
> 
> 
> So I think this is less likely a box64 issue, maybe someone can try this game on some AArch64 machine with a decent GPU.

You are right. Not a box64 issue.
I got it boot once on my new system. Then crashed - -
Anyway, the game is too much for the board.

```bash
rico [ /opt/games/the_universim ]$ ./box64-start.sh 
Dynarec for ARM64, with extension: ASIMD AES CRC32 PMULL ATOMICS SHA1 SHA2 PageSize:4096 Running on - with 8 cores
Will use hardware counter measured at 24.0 MHz emulating 3.0 GHz
Params database has 98 entries
Box64 with Dynarec v0.3.3 fcd46e2 built on Dec 28 2024 08:16:28
BOX64: Detected 48bits at least of address space
Counted 64 Env var
BOX64 LIB PATH: BOX64 BIN PATH: ./:bin/:/opt/rustc/bin/:/usr/local/bin/:/usr/bin/:/opt/ant/bin/:/opt/jdk/bin/:/opt/bin/
Looking for ./The Universim.x86_64
argv[1]="-force-opengl"
Rename process to "The Universim.x86_64"
Using emulated UnityPlayer.so
Using native(wrapped) libm.so.6
Using emulated /usr/lib/box64-x86_64-linux-gnu/libgcc_s.so.1
Using native(wrapped) libpthread.so.0
Using native(wrapped) libc.so.6
Using native(wrapped) ld-linux-x86-64.so.2
Using native(wrapped) libdl.so.2
Using native(wrapped) libutil.so.1
Using native(wrapped) librt.so.1
Using native(wrapped) libbsd.so.0
Set current directory to /opt/games/the_universim
Found path: /opt/games/the_universim/The Universim.x86_64
Loading in SingleInstance mode
Using native(wrapped) libX11.so.6
Using native(wrapped) libxcb.so.1
Using native(wrapped) libXau.so.6
Using native(wrapped) libXdmcp.so.6
Using native(wrapped) libXext.so.6
Using native(wrapped) libXcursor.so.1
Using native(wrapped) libXfixes.so.3
Using native(wrapped) libXrender.so.1
Using native(wrapped) libXinerama.so.1
Using native(wrapped) libXi.so.6
Using native(wrapped) libXrandr.so.2
Using native(wrapped) libXss.so.1
Using native(wrapped) libXxf86vm.so.1
Using native(wrapped) libGL.so.1
Using native(wrapped) libudev.so.1
./box64-start.sh: line 24:  2255 Killed                  box64 ./"The Universim.x86_64" -force-opengl
```

 
![The Universim-1](https://github.com/user-attachments/assets/d8ab1f4f-2d38-4420-9154-361c7d3b59f7)
![The Universim-2](https://github.com/user-attachments/assets/37d3d0f2-e032-49db-9f57-b8a5097371c5)
![The Universim-3](https://github.com/user-attachments/assets/d5ac4697-3825-4be6-b2e9-b3102e515798)

**Comment by ricoazzurro** [comment]
Working and updated.
https://github.com/ptitSeb/box86-compatibility-list/issues/556
