### ISSUE TITLE
Stardew Valley

### ISSUE THREAD

**Issue by barleyguy** [ptitSeb/box86-compatibility-list#515]
### Description

Fully working in a short test. Needed one missing dependency "lib faudio".****

### Tested on

Raspberry Pi 5, 4 GB. Box64

### Previous behavior

None reported

### Current behavior

Fully working

### Screenshots

Normal

### OpenGL

I don't believe this game uses OpenGL

### Additional Information

Stock Raspberry Pi OS Bookworm. Needs "lib faudio" dependency, otherwise stock.

**Comment by ptitSeb** [comment]
Duplicate of https://github.com/ptitSeb/box86-compatibility-list/issues/469

**Comment by ptitSeb** [comment]
There is a repport of this game already. Can you add your result on that ticket instead?
