### ISSUE TITLE
Shovel Knight Treasure Trove

### ISSUE THREAD

**Issue by barleyguy** [ptitSeb/box86-compatibility-list#517]
### Description

Fully working with keyboard. Game controller not detected.

### Tested on

Raspberry Pi 5, 4 GB

### Previous behavior

None reported.

### Current behavior

Fully working when played with keyboard.

### Screenshots

All normal.

### OpenGL

Not sure

### Additional Information

GOG Version. Simply copy directory and add box64 to the start.sh file.

**Comment by ptitSeb** [comment]
Can you use existing issue https://github.com/ptitSeb/box86-compatibility-list/issues/137 and add your result there instead?
