### ISSUE TITLE
Slay the Spire

### ISSUE THREAD

**Issue by barleyguy** [ptitSeb/box86-compatibility-list#518]
### Description

Fully working. Works best in Windowed mode. Fullscreen modes have issues if they don't match desktop resolution.

### Tested on

Raspberry Pi 5, 4 GB. Box64

### Previous behavior

None reported

### Current behavior

Fully working

### Screenshots

All normal in windowed mode

### OpenGL

Not sure

### Additional Information

GOG version. Just copy the directory and modify the "start.sh" file. No additional dependencies needed.

BTW, Slay the Spire is a Java application. It may be possible to get this working with a JRE instead of Box64.

**Comment by ptitSeb** [comment]
Can you add your result on the existing ticket instead https://github.com/ptitSeb/box86-compatibility-list/issues/295 ?
