### ISSUE TITLE
How to solve many problems of installation of Winetricks and Raspberry with box86.

### ISSUE THREAD

**Issue by Disidente** [ptitSeb/box86-compatibility-list#54]
t requires a Linux PC, or WSL2, and I suspect it can solve many installation problems. Basically you need to install everything you need on a real PC, and copy the .wine directory to the Raspberry, using the same Wine version, in this case, 5.22 with a fresh installation.

The problem is basically the incompatibility of Winetricks with Raspberry + box86. Winetricks works well on a real Linux PC. But once installed on a PC and making sure it works on a real PC, clone the .wine directory, and put it directly into the Raspberry. Using "winserver -k" before clone ".wine" directory. Is importante use the SAME USERNAME between machines and directorys (/home/pi) or your own. Some registry keys like HKLM (system.reg) and HKCU (user.reg)  can be edit manually in text mode, but in my case is not necesary.

I don't know and I don't assure the compatibility with Box86, neither the same author nor Wine does it, but I've done some Heavys "tests" with SpeechSDK, Mono and NetFramework 4.8, and it worked in Raspberry with my own programs in .NET.

In PC, I have tried to install msxml3, and netFramework 4.8 manually without using winetricks. Downloading the respective .msi installation and installing with "wine start ...." for solve the bug "warning: This package (dotnet48) is broken in wine-5.22. Broken since 5.18. See https://bugs.winehq.org/show_bug.cgi?id=49897 for more info. Use --force to try anyway."

I hope that this type of proposal solves many other incompatibilities of the rest of the users.

Still working....

**Comment by WheezyE** [comment]
This is can be a nice workaround for testing.  It's helpful to tar the x86 Linux pre-made wineprefix (so that symlinks are preserved) before copying it to a flash drive and then pasting it on the Pi.  I like to refer to this method as "side-loading" the wineprefix.  

Ideally, software should be able to install through winetricks & box86 without needing to side-load a prefix, but this can be helpful in cases where people just want to get software working on the Pi and don't need an elegant installation process.

**Comment by nru1979** [comment]
I personally do my custom wineprefixes (eg:ddr=gdi) in a stretch/stretch chrooted x86 environment on my pi. You need enough storage to hold that system though.

It would still be a big gain if someone forked a winetricks to work with a portable wine x86 version though. So far winetricks will always launch the default wine (the arm wine) making it unusable with box86.

**Comment by WheezyE** [comment]
That’s a cool idea w chroot. I haven’t tried that yet.

No need to use ARM wine though.  Box86 is designed to use i386 Wine even on ARM computers. ARM Wine (or wine installed on a Pi or ARM system with apt-get) is not recommended to use with Box86.  Just download the two main i386 wine deb files for the version of wine you wish to use:

Install wine
```
# Backup old wine
sudo mv ~/wine ~/wine-old
sudo mv ~/.wine ~/.wine-old
sudo mv /usr/local/bin/wine /usr/local/bin/wine-old
sudo mv /usr/local/bin/winecfg /usr/local/bin/winecfg-old
sudo mv /usr/local/bin/wineserver /usr/local/bin/wineserver-old

# Download
cd ~/Downloads
wget https://dl.winehq.org/wine-builds/debian/dists/buster/main/binary-i386/wine-devel-i386_5.21~buster_i386.deb
wget https://dl.winehq.org/wine-builds/debian/dists/buster/main/binary-i386/wine-devel_5.21~buster_i386.deb
dpkg-deb -xv wine-devel-i386_5.21~buster_i386.deb wine-installer
dpkg-deb -xv wine-devel_5.21~buster_i386.deb wine-installer

# Install
sudo mv wine-installer/opt/wine-devel ~/wine
sudo ln -s ~/wine/bin/wine /usr/local/bin/wine
sudo ln -s ~/wine/bin/winecfg /usr/local/bin/winecfg
sudo ln -s ~/wine/bin/wineserver /usr/local/bin/wineserver

# Boot wine (make fresh wineprefix in ~/.wine )
wine wineboot
```

Winetricks also works fine with Box86 and i386 Wine (tested on an RPi4):

Install winetricks
```
# Backup old winetricks
sudo mv /usr/local/bin/winetricks /usr/local/bin/winetricks-old

# Download
cd ~/Downloads
wget https://raw.githubusercontent.com/Winetricks/winetricks/master/src/winetricks

# Install
sudo chmod +x winetricks
sudo cp winetricks /usr/local/bin

# winetricks needs this installed
sudo apt-get install cabextract -y 
```

Run winetricks like this:
```
BOX86_NOBANNER=1 winetricks dotnet20sp2
```

**Comment by nru1979** [comment]
Hello,
I need wine-arm on my pi so I can run libd2game.
If Seb starts working one day on Diablo 2 and makes it work, i will probably drop libd2game and wine-arm.
But since there is a perfectly working Diablo 2 availlable for Pi I don't think it must be a priority... 
Thus, having wine-arm as primary wine breaks winetricks from working :-(

**Comment by WheezyE** [comment]
Maybe you could install both and then have a script that you run that switches the destination of the `usr/local/bin/wine` symlink?

**Comment by ptitSeb** [comment]
I think Diablo 2 works? At least I have some some multiplayers mod working.
But yeah, wine-arm is usefull only for Diablo2 static recompile (and StarCraft I static recompile too I guess).

**Comment by nru1979** [comment]
@ptitSeb Opened Diablo II issue.
@WheezyE I usually do my own bash scripts where I mention wine full path.
What I miss so far is a way to tell winetricks to use my portable wine dir. But yeah I might try symlinks, might be a good idea!

**Comment by ptitSeb** [comment]
Yeah, I have seen. But I prefer to have issue open on box86 repo, and keep here status of games running only (issue are not meant to be closed here).
