### ISSUE TITLE
Diablo II

### ISSUE THREAD

**Issue by nru1979** [ptitSeb/box86-compatibility-list#55]
Sorry pal, Diablo II does SIGSEGV

Tests done:
D2VidTst.exe (crashes before the end)
D2VidTst.exe skip test, force choose direct draw
Game
--> SIGSEGV
D2VidTst.exe skip test force choose direct 3D
Game 
--> SIGSEGV
Game -3dfx
--> SIGSEGV

Version: PI 3B+ Raspbian buster 3G/1G 256 mb /var/swap 
Wine 3.20 Playonlinux
box86 0.1.7
Diablo II 1.13
Screenshot:
![2020-12-08-200941_1920x1080_scrot](https://user-images.githubusercontent.com/75307620/101530436-35780a80-3992-11eb-96fa-550533bd9882.png)

**Comment by ptitSeb** [comment]
Oh, ok. Tant pis.

Looks like a null function jump (maybe that libpng12 this time?). I'll check this game at one point, I heve the 3 CDs lying somewhere...

**Comment by nru1979** [comment]
That libpng12 message appears since I did apt-get install libpng12-0 for the other game.
Note that despite the libpng12 spam heroes 4 now runs here without crashes (I had to increase the swap file, seems that H4 is extremely ressource-hungry)
Diablo 2 is not really urgent, but the risk is if the seeds of libd2game die, it will be like exagear, nowhere to be found.

**Comment by nru1979** [comment]
Ill move this issue to box86 main issue list later on. It takes a little time to understand which goes where… (especially the bound working/not working game)

**Comment by Zack7765** [comment]
I have the same problems on my Pi 4B.

**Comment by nru1979** [comment]
Now double with #88 
Closing this issue
