### ISSUE TITLE
Baldur's Gate: Enhanced Edition

### ISSUE THREAD

**Issue by brzegorz** [ptitSeb/box86-compatibility-list#76]
### Tested on
Pinebook Pro

### Status
**Previous behavior:** 
None reported

**Current behavior:**
Works well. Mods, including SCS and BG1 NPC Project, are installable and work. Performance is decent, though the game is a bit stuttery. I've played for a few hours now without any issues.

**Comment by ptitSeb** [comment]
Can you put a screenshot please.

**Comment by rajdakin** [comment]
Missing quite a few details, closing since there is also another (better) issue for Baldur's Gate Enhanced Edition.
