### ISSUE TITLE
Highway Pursuit 1.1 for Windows

### ISSUE THREAD

**Issue by dosxga** [ptitSeb/box86-compatibility-list#97]
works but have to use alt+tab or mess with it when first start

**Comment by ptitSeb** [comment]
Can you put a screenshot a bit more detail (look at other compatibility reports)?

**Comment by dosxga** [comment]
got it to work perfectly now, don't know if it uses box86 or wine updates fixed it, so no.  I think my machines updated to wine staging 6.9, I'll close

**Comment by ptitSeb** [comment]
Can you open a compatibity ticket for this game, using the Template and a nice Screenshot of the game running?
